"""
Pricing constants for TCA-Compiler experiments.

All prices in USD per token (computed from per-MTok prices).
Update these if Anthropic pricing changes; the TCA framework is
provider-agnostic but our experiments use Anthropic's tier model.

Reference: https://www.anthropic.com/pricing
"""
from __future__ import annotations
from typing import Literal

Tier = Literal["haiku", "sonnet", "opus"]

# Per-token prices in USD, derived from per-MTok published prices.
# Format: {tier: {"input": price_per_input_token, "output": price_per_output_token}}
TIER_PRICING: dict[Tier, dict[str, float]] = {
    "haiku": {
        "input":  1.00 / 1_000_000,   # $1.00 per MTok
        "output": 5.00 / 1_000_000,   # $5.00 per MTok
    },
    "sonnet": {
        "input":  3.00 / 1_000_000,   # $3.00 per MTok
        "output": 15.00 / 1_000_000,  # $15.00 per MTok
    },
    "opus": {
        "input":  5.00 / 1_000_000,   # $5.00 per MTok
        "output": 25.00 / 1_000_000,  # $25.00 per MTok
    },
}

# Concrete model identifiers for each tier.
TIER_MODELS: dict[Tier, str] = {
    "haiku":  "claude-haiku-4-5-20251001",
    "sonnet": "claude-sonnet-4-6",
    "opus":   "claude-opus-4-7",
}

# Context window sizes per tier (used by GraphRewriter T1 fusion guards).
CONTEXT_WINDOW: dict[Tier, int] = {
    "haiku":  200_000,
    "sonnet": 200_000,
    "opus":   200_000,
}

# Tier ordering for escalation logic.
TIER_ORDER: list[Tier] = ["haiku", "sonnet", "opus"]


def cost_inference(
    input_tokens: int,
    output_tokens: int,
    tier: Tier,
    cache_read_tokens: int = 0,
) -> float:
    """
    Compute inference cost in USD.

    Cache-read tokens are billed at 10% of input price (Anthropic policy).
    Args:
        input_tokens: total input tokens including memory injection
        output_tokens: tokens generated by the model
        tier: model tier
        cache_read_tokens: tokens served from prompt cache (subset of input_tokens)

    Returns:
        Inference cost in USD.
    """
    if cache_read_tokens > input_tokens:
        raise ValueError(
            f"cache_read_tokens ({cache_read_tokens}) cannot exceed "
            f"input_tokens ({input_tokens})"
        )
    pricing = TIER_PRICING[tier]
    p_in = pricing["input"]
    p_out = pricing["output"]
    cache_price = p_in * 0.10  # Anthropic cache hit pricing

    uncached_input = input_tokens - cache_read_tokens
    return (
        uncached_input * p_in
        + cache_read_tokens * cache_price
        + output_tokens * p_out
    )


def cost_memory_injection(
    injection_tokens: int,
    tier: Tier,
) -> float:
    """
    Compute memory injection cost in USD.

    Memory tokens are billed at input price of the executing tier.
    This is the coupling effect from Theorem 2: higher tier =
    higher injection cost for the same tokens.
    """
    return injection_tokens * TIER_PRICING[tier]["input"]
